CREATE TABLE training_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    day_of_week VARCHAR(20) NOT NULL
);

CREATE TABLE exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    muscle_group VARCHAR(255) NOT NULL,
    training_day_id BIGINT NOT NULL,
    CONSTRAINT fk_exercises_training_day
        FOREIGN KEY (training_day_id) REFERENCES training_days (id)
);

CREATE TABLE set_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id BIGINT NOT NULL,
    week INTEGER NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    reps INTEGER NOT NULL,
    sets INTEGER NOT NULL,
    date DATE NOT NULL,
    CONSTRAINT fk_set_logs_exercise
        FOREIGN KEY (exercise_id) REFERENCES exercises (id)
);

CREATE TABLE water_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    consumed_ml INTEGER NOT NULL,
    goal_ml INTEGER NOT NULL
);

CREATE TABLE settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_goal_ml INTEGER NOT NULL,
    bottle_size_ml INTEGER NOT NULL
);
