ALTER TABLE exercises ADD COLUMN series_validas INTEGER NOT NULL DEFAULT 3;

CREATE TABLE sessoes_exercicio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id BIGINT NOT NULL,
    semana INTEGER NOT NULL,
    data DATE NOT NULL,
    CONSTRAINT fk_sessoes_exercicio_exercise
        FOREIGN KEY (exercise_id) REFERENCES exercises (id)
);

CREATE TABLE series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_exercicio_id BIGINT NOT NULL,
    posicao INTEGER NOT NULL,
    carga DOUBLE PRECISION NOT NULL,
    reps INTEGER NOT NULL,
    CONSTRAINT fk_series_sessao
        FOREIGN KEY (sessao_exercicio_id) REFERENCES sessoes_exercicio (id)
);
